/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Peliculas;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


public class FrmBuscarPelicula extends javax.swing.JFrame {
 ImageIcon imag = new ImageIcon(getClass().getResource("/imagenes/azul.jpg"));   
    ImageIcon icon;
    DefaultTableModel tabla = new DefaultTableModel();
    ResultSet rstTabla= null;
    Peliculas peli= new Peliculas();
    ResultSet rstId=null;
     ResultSet rstnombre=null;
   
    public FrmBuscarPelicula() {
        initComponents();
        this.icon = new ImageIcon(imag.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
          lblFondo.setIcon(icon);
           
        tlbPeliculas.setModel(tabla);
        llenarTablaPeliculas();
    }
    public void llenarTablaPeliculas(){ 
        Object Encabezados[]={"id de peliculas","nombre"};
        tabla.setColumnIdentifiers(Encabezados);
       for (int i = 0; i < tlbPeliculas.getRowCount(); i++) {
            tabla.removeRow(i);
            i-=1;
        }
        rstTabla= peli.llenarPeliculas();
        try {
            while(rstTabla.next()){
                tabla.addRow(new Object[]{rstTabla.getInt(1),rstTabla.getString(2)});
                
            } 
                    } catch (SQLException ex) {
            Logger.getLogger(FrmBuscarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public void BuscarPelicula(){
        String vacio="";
        rstId=peli.buscarId(vacio);
        rstnombre=peli.buscarPeliculas(vacio);
    
         Object Encabezados[]={"id de peliculas","nombre"};
        tabla.setColumnIdentifiers(Encabezados);
       for (int i = 0; i < tlbPeliculas.getRowCount(); i++) {
            tabla.removeRow(i);
            i-=1;
        }
        
        try {
            while(rstId.next()){
                if (txtbuscar==rstId){
                    tabla.addRow(new Object[]{rstId.getInt(1),rstId.getString(2)});
                } 
            } 
                    } catch (SQLException ex) {
            Logger.getLogger(FrmBuscarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rstnombre.next()){
                if (txtbuscar==rstnombre){
                    tabla.addRow(new Object[]{rstnombre.getInt(1),rstnombre.getString(2)});
                } 
            } 
                    } catch (SQLException ex) {
            Logger.getLogger(FrmBuscarPelicula.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tlbPeliculas.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        lblbuscar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbPeliculas = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 37, 220, 30));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search_plus.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 30));

        lblbuscar1.setText("Buscar:");
        getContentPane().add(lblbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, -1));

        tlbPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tlbPeliculas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 370, 210));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        BuscarPelicula();
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblbuscar1;
    private javax.swing.JTable tlbPeliculas;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
